packages:
  - apps/*
  - packages/*
  - themes/*
  - tests/*

catalog:
  '@chenglou/pretext': ^0.0.8
  '@slidev/cli': 52.19.0
  '@slidev/client': 52.19.0
  '@slidev/theme-default': 0.25.0
  '@slidev/types': 52.19.0
  '@types/node': ^26.1.2
  lucide: ^0.544.0
  pptxgenjs: ^4.0.1
  prismjs: ^1.30.0
  typescript: ^6.0.3
  vite: 8.2.0
  vitest: ^4.1.10
  zod: ^4.0.14

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
