import assert from "node:assert/strict";
import { createServer } from "node:http";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createStudio } from "./server.js";
import { prepareStaging, recoverTransactions } from "./transaction.js";

const root = await mkdtemp(path.join(os.tmpdir(), "fastppt-studio-"));
await mkdir(path.join(root, "svg_output"));
await writeFile(path.join(root, "svg_output", "P01.svg"), '<svg xmlns="http://www.w3.org/2000/svg"><text id="title">Hi</text></svg>');
const staging = await prepareStaging(root, path.join(root, "interaction"), "staging_smoke", ["P01"]);
assert.equal(await readFile(path.join(staging, "svg_output", "P01.svg"), "utf8"), '<svg xmlns="http://www.w3.org/2000/svg"><text id="title">Hi</text></svg>');
const app = await createStudio(root);
assert.equal((await app.inject({ method: "GET", url: "/healthz" })).statusCode, 200);
assert.match((await app.inject({ method: "GET", url: "/" })).body, /FastPPT/);
assert.match((await app.inject({ method: "GET", url: `/projects/${encodeURIComponent(path.basename(root))}` })).body, /FastPPT/);
const mismatchedProjectRoute = await app.inject({ method: "GET", url: "/projects/another-project" });
assert.equal(mismatchedProjectRoute.statusCode, 302);
assert.equal(mismatchedProjectRoute.headers.location, `/projects/${encodeURIComponent(path.basename(root))}`);
assert.equal((await app.inject({ method: "GET", url: "/api/workflow/confirmations" })).json().confirmed, false);
assert.equal((await app.inject({ method: "GET", url: "/api/workflow/confirm/session" })).statusCode, 200);
assert.equal((await app.inject({ method: "GET", url: "/api/workflow/intake" })).json().status, "empty");
const projectParent = await mkdtemp(path.join(os.tmpdir(), "fastppt-projects-"));
const launcherRoot = path.join(projectParent, "current"); const siblingRoot = path.join(projectParent, "recent");
await mkdir(path.join(launcherRoot, "interaction"), { recursive: true }); await mkdir(path.join(siblingRoot, "interaction"), { recursive: true }); await mkdir(path.join(launcherRoot, "svg_output")); await writeFile(path.join(launcherRoot, "svg_output", "P01.svg"), "<svg/>");
let launchedProject = "", launchedPort = 0;
const launcherApp = await createStudio(launcherRoot, { projectInitializer: async (name, parent) => { const created = path.join(parent, name); await mkdir(path.join(created, "interaction"), { recursive: true }); return created; }, projectLauncher: async (project, port) => { launchedProject = project; launchedPort = port; } });
const discoveredProjects = (await launcherApp.inject({ method: "GET", url: "/api/projects" })).json().projects;
assert.deepEqual(new Set(discoveredProjects.map((project: { name: string }) => project.name)), new Set(["current", "recent"]));
assert.equal((await launcherApp.inject({ method: "POST", url: "/api/projects/open", payload: { action: "open", projectId: "current" } })).json().url, "/projects/current");
const openedProject = (await launcherApp.inject({ method: "POST", url: "/api/projects/open", payload: { action: "open", projectId: "recent" } })).json();
assert.match(openedProject.url, /^http:\/\/127\.0\.0\.1:\d+\/projects\/recent$/); assert.equal(launchedProject, siblingRoot); assert.ok(launchedPort > 0);
const createdProject = (await launcherApp.inject({ method: "POST", url: "/api/projects/open", payload: { action: "create", name: "同名演示", note: "第一次" } })).json();
assert.match(createdProject.projectId, /^project_/); assert.match(createdProject.url, new RegExp(`/projects/${createdProject.projectId}$`)); assert.match(launchedProject, /fastppt-/);
const duplicateNameProject = (await launcherApp.inject({ method: "POST", url: "/api/projects/open", payload: { action: "create", name: "同名演示", note: "第二次" } })).json();
assert.notEqual(duplicateNameProject.projectId, createdProject.projectId);
const projectsAfterCreate = (await launcherApp.inject({ method: "GET", url: "/api/projects" })).json().projects;
assert.equal(projectsAfterCreate.filter((project: { name: string }) => project.name === "同名演示").length, 2);
assert.ok(projectsAfterCreate.some((project: { projectId: string; note?: string }) => project.projectId === createdProject.projectId && project.note === "第一次"));
assert.equal((await launcherApp.inject({ method: "POST", url: "/api/projects/open", payload: { action: "open", projectId: "missing" } })).statusCode, 404);
assert.equal((await launcherApp.inject({ method: "POST", url: "/api/projects/open", payload: { action: "open", projectId: "../unsafe" } })).statusCode, 422);
await launcherApp.close();
const uploaded = (await app.inject({ method: "POST", url: "/api/uploads", payload: { name: "course brief.md", content: Buffer.from("# Uploaded").toString("base64") } })).json();
assert.match(uploaded.source, /^uploads\/course_brief-\d+\.md$/);
assert.equal(await readFile(path.join(root, uploaded.source), "utf8"), "# Uploaded");
assert.equal((await app.inject({ method: "POST", url: "/api/uploads", payload: { name: "malware.exe", content: Buffer.from("x").toString("base64") } })).statusCode, 415);
const topicIntake = (await app.inject({ method: "POST", url: "/api/workflow/intake", payload: { topic: "可持续校园", provider: "codex" } })).json();
assert.equal(topicIntake.status, "research_required");
assert.match(topicIntake.sessionId, /^session_/);
const researchRoot = await mkdtemp(path.join(os.tmpdir(), "fastppt-research-"));
await mkdir(path.join(researchRoot, "svg_output")); await writeFile(path.join(researchRoot, "svg_output", "P01.svg"), "<svg/>");
let researchImports: string[] = [];
const researchApp = await createStudio(researchRoot, {
  researcher: async () => JSON.stringify({ markdown: "## Research Brief\n\n### 能源基线\n校园建筑用能可按年度统计。[F001]", facts: { schema: "ppt-master.fact-provenance.v1", topic: "可持续校园", facts: [{ fact_id: "F001", claim: "校园建筑用能可按年度统计。", source_title: "Campus energy guidance", source_url: "https://example.org/energy", classification: "external", retrieved_at: "2026-09-01" }] } }),
  importer: async (_project, sourcePaths) => { researchImports = sourcePaths; return { code: 0, stdout: "imported", stderr: "" }; },
});
await researchApp.inject({ method: "POST", url: "/api/workflow/intake", payload: { topic: "可持续校园" } });
const researched = (await researchApp.inject({ method: "POST", url: "/api/workflow/research/run" })).json();
assert.equal(researched.status, "sources_ready"); assert.equal(researched.research.factCount, 1);
assert.match(await readFile(path.join(researchRoot, researched.research.markdown), "utf8"), /^## Research Brief/);
assert.equal(JSON.parse(await readFile(path.join(researchRoot, researched.research.facts), "utf8")).facts[0].fact_id, "F001");
assert.equal((await researchApp.inject({ method: "POST", url: "/api/workflow/intake/import" })).json().status, "imported");
assert.deepEqual(researchImports, researched.sources.map((source: string) => path.join(researchRoot, source)));
await researchApp.close();
const invalidResearchRoot = await mkdtemp(path.join(os.tmpdir(), "fastppt-research-invalid-")); await mkdir(path.join(invalidResearchRoot, "svg_output")); await writeFile(path.join(invalidResearchRoot, "svg_output", "P01.svg"), "<svg/>");
const invalidResearchApp = await createStudio(invalidResearchRoot, { researcher: async () => JSON.stringify({ markdown: "## Research Brief\nhttps://example.org [F002]", facts: { schema: "ppt-master.fact-provenance.v1", topic: "Invalid", facts: [{ fact_id: "F002", claim: "Invalid", source_title: "Invalid", source_url: "https://example.org", classification: "external", retrieved_at: "2026-09-01" }] } }) });
await invalidResearchApp.inject({ method: "POST", url: "/api/workflow/intake", payload: { topic: "Invalid" } });
assert.equal((await invalidResearchApp.inject({ method: "POST", url: "/api/workflow/research/run" })).statusCode, 422);
assert.equal((await invalidResearchApp.inject({ method: "GET", url: "/api/workflow/intake" })).json().status, "research_failed");
await invalidResearchApp.close();
await mkdir(path.join(root, "uploads"), { recursive: true });
await writeFile(path.join(root, "uploads", "brief.md"), "# Brief");
assert.equal((await app.inject({ method: "POST", url: "/api/workflow/intake", payload: { topic: "课程介绍", sources: ["uploads/brief.md"], provider: "claude" } })).json().status, "sources_ready");
assert.equal((await app.inject({ method: "POST", url: "/api/workflow/intake", payload: { topic: "unsafe", sources: ["../secret.md"] } })).statusCode, 400);
const importRoot = await mkdtemp(path.join(os.tmpdir(), "fastppt-import-"));
await mkdir(path.join(importRoot, "svg_output")); await mkdir(path.join(importRoot, "uploads"));
await writeFile(path.join(importRoot, "svg_output", "P01.svg"), "<svg/>"); await writeFile(path.join(importRoot, "uploads", "brief.md"), "brief");
let importedPaths: string[] = [];
const importApp = await createStudio(importRoot, { importer: async (_project, sources) => { importedPaths = sources; return { code: 0, stdout: "imported", stderr: "" }; } });
await importApp.inject({ method: "POST", url: "/api/workflow/intake", payload: { topic: "Import", sources: ["uploads/brief.md"] } });
const importedIntake = (await importApp.inject({ method: "POST", url: "/api/workflow/intake/import" })).json();
assert.equal(importedIntake.status, "imported"); assert.equal(importedIntake.receipt.returncode, 0);
assert.deepEqual(importedPaths, [path.join(importRoot, "uploads", "brief.md")]);
await importApp.close();
const plannerRoot = await mkdtemp(path.join(os.tmpdir(), "fastppt-planner-"));
await mkdir(path.join(plannerRoot, "svg_output")); await writeFile(path.join(plannerRoot, "svg_output", "P01.svg"), "<svg/>");
const plannerApp = await createStudio(plannerRoot, { researcher: async () => JSON.stringify({ markdown: "## Research Brief\n\n### 基线\n人工智能课程覆盖基础概念。[F001]", facts: { schema: "ppt-master.fact-provenance.v1", topic: "人工智能导论", facts: [{ fact_id: "F001", claim: "人工智能课程覆盖基础概念。", source_title: "AI curriculum", source_url: "https://example.org/ai", classification: "external", retrieved_at: "2026-09-01" }] } }), importer: async () => ({ code: 0, stdout: "imported", stderr: "" }), planner: async () => JSON.stringify({ title: "AI 课程", audience: "本科生", tone: "学术", canvas: "ppt169", pages: [{ id: "P01", role: "title", title: "人工智能导论" }] }) });
await plannerApp.inject({ method: "POST", url: "/api/workflow/intake", payload: { topic: "人工智能导论" } });
await plannerApp.inject({ method: "POST", url: "/api/workflow/research/run" }); await plannerApp.inject({ method: "POST", url: "/api/workflow/intake/import" });
const generatedPlan = (await plannerApp.inject({ method: "POST", url: "/api/workflow/plan/run" })).json();
assert.equal(generatedPlan.status, "awaiting_confirmation"); assert.equal(generatedPlan.pages[0].role, "title");
assert.equal((await plannerApp.inject({ method: "GET", url: "/api/workflow/intake" })).json().status, "planned");
await plannerApp.close();
const invalidPlannerRoot = await mkdtemp(path.join(os.tmpdir(), "fastppt-planner-invalid-")); await mkdir(path.join(invalidPlannerRoot, "svg_output")); await writeFile(path.join(invalidPlannerRoot, "svg_output", "P01.svg"), "<svg/>");
const invalidPlannerApp = await createStudio(invalidPlannerRoot, { researcher: async () => JSON.stringify({ markdown: "## Research Brief\n\nNo external facts retained.", facts: { schema: "ppt-master.fact-provenance.v1", topic: "Invalid", facts: [] } }), importer: async () => ({ code: 0, stdout: "imported", stderr: "" }), planner: async () => "not json" }); await invalidPlannerApp.inject({ method: "POST", url: "/api/workflow/intake", payload: { topic: "Invalid" } });
await invalidPlannerApp.inject({ method: "POST", url: "/api/workflow/research/run" }); await invalidPlannerApp.inject({ method: "POST", url: "/api/workflow/intake/import" });
assert.equal((await invalidPlannerApp.inject({ method: "POST", url: "/api/workflow/plan/run" })).statusCode, 422);
assert.equal((await invalidPlannerApp.inject({ method: "GET", url: "/api/workflow/plan" })).statusCode, 404);
await invalidPlannerApp.close();
const generationRoot = await mkdtemp(path.join(os.tmpdir(), "fastppt-generation-")); await mkdir(path.join(generationRoot, "interaction"), { recursive: true });
await writeFile(path.join(generationRoot, "interaction", "page_plan.json"), JSON.stringify({ status: "confirmed", canvas: "ppt169", pages: [{ id: "P01", role: "title", title: "Opening" }] }));
const generationApp = await createStudio(generationRoot, { checker: async () => ({ code: 0, stdout: "passed", stderr: "" }), generator: async () => '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 720"><text id="title">Opening</text></svg>' });
const generatedFirst = (await generationApp.inject({ method: "POST", url: "/api/workflow/generate-first" })).json(); assert.equal(generatedFirst.status, "completed");
assert.match(await readFile(path.join(generationRoot, "svg_output", "P01.svg"), "utf8"), /Opening/); await generationApp.close();
const failedGenerationRoot = await mkdtemp(path.join(os.tmpdir(), "fastppt-generation-failed-")); await mkdir(path.join(failedGenerationRoot, "interaction"), { recursive: true }); await writeFile(path.join(failedGenerationRoot, "interaction", "page_plan.json"), JSON.stringify({ status: "confirmed", canvas: "ppt169", pages: [{ id: "P01", role: "title", title: "Opening" }] }));
const failedGenerationApp = await createStudio(failedGenerationRoot, { checker: async () => ({ code: 1, stdout: "", stderr: "invalid" }), generator: async () => '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 720"/>' });
assert.equal((await failedGenerationApp.inject({ method: "POST", url: "/api/workflow/generate-first" })).statusCode, 422);
assert.equal((await failedGenerationApp.inject({ method: "GET", url: "/api/slides" })).json().slides[0].revision, null); await failedGenerationApp.close();
const deckGenerationRoot = await mkdtemp(path.join(os.tmpdir(), "fastppt-generation-deck-")); await mkdir(path.join(deckGenerationRoot, "interaction"), { recursive: true }); await writeFile(path.join(deckGenerationRoot, "interaction", "page_plan.json"), JSON.stringify({ status: "confirmed", canvas: "ppt169", pages: [{ id: "P01", role: "title", title: "Opening" }, { id: "P02", role: "content", title: "Detail" }] }));
const deckGenerationApp = await createStudio(deckGenerationRoot, { checker: async () => ({ code: 0, stdout: "passed", stderr: "" }), generator: async (_provider, prompt) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 720"><text>${prompt.includes("P02") ? "Detail" : "Opening"}</text></svg>` });
const generatedDeck = (await deckGenerationApp.inject({ method: "POST", url: "/api/workflow/generate-all" })).json(); assert.deepEqual(generatedDeck.slides, ["P01", "P02"]); assert.equal((await deckGenerationApp.inject({ method: "GET", url: "/api/slides" })).json().slides.length, 2); await deckGenerationApp.close();
const partialGenerationRoot = await mkdtemp(path.join(os.tmpdir(), "fastppt-generation-partial-")); await mkdir(path.join(partialGenerationRoot, "interaction"), { recursive: true }); await writeFile(path.join(partialGenerationRoot, "interaction", "page_plan.json"), JSON.stringify({ status: "confirmed", canvas: "ppt169", pages: [{ id: "P01", role: "title", title: "Opening" }, { id: "P02", role: "content", title: "Detail" }] }));
const partialGenerationApp = await createStudio(partialGenerationRoot, { checker: async () => ({ code: 0, stdout: "passed", stderr: "" }), generator: async (_provider, prompt) => prompt.includes('"id": "P02"') ? "invalid" : '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 720"/>' }); assert.equal((await partialGenerationApp.inject({ method: "POST", url: "/api/workflow/generate-all" })).statusCode, 422); assert.ok((await partialGenerationApp.inject({ method: "GET", url: "/api/slides" })).json().slides.every((slide: { revision: null }) => slide.revision === null)); await partialGenerationApp.close();
const generationSession = (await app.inject({ method: "POST", url: "/api/harness/sessions", payload: { kind: "codex", purpose: "generation", context: { topic: "Studio" } } })).json();
assert.match(generationSession.sessionId, /^session_/);
const revisionSession = (await app.inject({ method: "POST", url: `/api/harness/sessions/${generationSession.sessionId}/fork`, payload: { purpose: "page_revision", context: { slide: "P01" } } })).json();
assert.equal(revisionSession.parentSessionId, generationSession.sessionId);
assert.equal(revisionSession.kind, "codex");
assert.equal((await app.inject({ method: "POST", url: `/api/harness/sessions/${revisionSession.sessionId}/resume` })).json().status, "idle");
assert.equal((await app.inject({ method: "POST", url: `/api/harness/sessions/${revisionSession.sessionId}/cancel` })).json().status, "canceled");
assert.equal((await app.inject({ method: "POST", url: `/api/harness/sessions/${revisionSession.sessionId}/resume` })).statusCode, 409);
const persistedSessions = (await app.inject({ method: "GET", url: "/api/harness/sessions" })).json().sessions;
assert.equal(persistedSessions.length, 4);
assert.equal(persistedSessions.filter((session: { purpose: string }) => session.purpose === "planning").length, 2);
assert.equal((await app.inject({ method: "GET", url: "/api/workflow/plan" })).statusCode, 404);
assert.equal((await app.inject({ method: "POST", url: "/api/workflow/plan", payload: { title: "Incomplete" } })).statusCode, 422);
const plan = (await app.inject({ method: "POST", url: "/api/workflow/plan", payload: { title: "课程首页", audience: "本科生", tone: "学术、克制", canvas: "ppt43", pages: [{ id: "P01", role: "title", title: "课程名称" }] } })).json();
assert.equal((await app.inject({ method: "POST", url: "/api/workflow/plan", payload: { ...plan, themeColor: "#123456", template: "free-design" } })).statusCode, 200);
assert.equal((await app.inject({ method: "POST", url: "/api/workflow/plan", payload: { ...plan, themeColor: "blue" } })).statusCode, 422);
assert.equal(plan.status, "awaiting_confirmation");
assert.ok(["待确认", "可导出"].includes((await app.inject({ method: "GET", url: "/api/slides" })).json().slides[0].statusLabel));
assert.equal((await app.inject({ method: "GET", url: "/api/workflow/plan" })).json().pages[0].role, "title");
assert.equal((await app.inject({ method: "GET", url: "/api/project" })).json().stage, "planning");
const slides = (await app.inject({ method: "GET", url: "/api/slides" })).json();
assert.equal(slides.slides[0].id, "P01");
const elementResult = (await app.inject({ method: "GET", url: "/api/slides/P01/elements" })).json();
assert.equal(elementResult.elements[0].id, "title");
assert.match(elementResult.elements[0].structuralPath, /^\/svg/);
assert.equal((await app.inject({ method: "POST", url: "/api/slides/P01/resolve-element", payload: { revision: elementResult.revision, elementId: "title" } })).json().status, "exact");
assert.equal((await app.inject({ method: "POST", url: "/api/slides/P01/resolve-element", payload: { revision: `sha256:${"0".repeat(64)}`, elementId: "old", tag: elementResult.elements[0].tag, structuralPath: elementResult.elements[0].structuralPath, bbox: elementResult.elements[0].bbox, textDigest: elementResult.elements[0].textDigest } })).json().status, "relocated");
assert.equal((await app.inject({ method: "POST", url: "/api/slides/P01/resolve-element", payload: { revision: `sha256:${"0".repeat(64)}`, elementId: "old" } })).statusCode, 409);
assert.equal((await app.inject({ method: "GET", url: "/api/slides/%2e%2e%2fsecret/raw" })).statusCode, 400);
assert.equal((await app.inject({ method: "GET", url: "/api/conversations/invalid/P01" })).statusCode, 400);
assert.equal((await app.inject({ method: "POST", url: "/api/conversations/page/P01/messages", payload: { content: "x", attachments: [{ path: "../secret" }] } })).statusCode, 400);
const job = await app.inject({ method: "POST", url: "/api/jobs", payload: { scope: "page", targets: [{ slide: "P01" }], baseRevisions: { P01: slides.slides[0].revision }, intent: "调整标题", mode: "agent", exportAfter: false } });
assert.equal(job.statusCode, 200);
const sessionJob = await app.inject({ method: "POST", url: "/api/jobs", payload: { scope: "page", targets: [{ slide: "P01" }], baseRevisions: { P01: slides.slides[0].revision }, intent: "session edit", mode: "agent", exportAfter: false, sessionId: generationSession.sessionId } });
assert.equal(sessionJob.json().sessionId, generationSession.sessionId);
assert.equal((await app.inject({ method: "POST", url: "/api/jobs", payload: { scope: "page", targets: [{ slide: "P01" }], baseRevisions: { P01: slides.slides[0].revision }, intent: "missing session", mode: "agent", exportAfter: false, sessionId: "session_missing" } })).statusCode, 404);
assert.equal((await app.inject({ method: "POST", url: "/api/jobs", payload: { scope: "page", targets: [{ slide: "P01" }], baseRevisions: {}, intent: "x", mode: "agent", exportAfter: false } })).statusCode, 422);
assert.equal((await app.inject({ method: "POST", url: "/api/jobs", payload: { scope: "selection", targets: [{ slide: "P01" }], baseRevisions: { P01: slides.slides[0].revision }, intent: "x", mode: "agent", exportAfter: false } })).statusCode, 422);
assert.equal((await app.inject({ method: "POST", url: `/api/jobs/${job.json().jobId}/poll` })).json().status, "queued");
const jobDetail = (await app.inject({ method: "GET", url: `/api/jobs/${job.json().jobId}` })).json();
assert.equal(jobDetail.plan.slides[0], "P01");
assert.deepEqual(jobDetail.events.map((event: { type: string }) => event.type), ["job.created", "job.plan_ready"]);
const runEvents = (await app.inject({ method: "GET", url: `/api/events?stream=0&topics=run:${job.json().jobId}` })).json().events;
assert.deepEqual(runEvents.map((event: { type: string }) => event.type), ["job.created", "job.plan_ready"]);
assert.ok(runEvents.every((event: { topics: string[] }) => event.topics.includes(`run:${job.json().jobId}`)));
assert.equal((await app.inject({ method: "GET", url: "/api/events?stream=0&topics=run:missing" })).json().events.length, 0);
const sessionEvents = (await app.inject({ method: "GET", url: `/api/events?stream=0&topics=session:${generationSession.sessionId}` })).json().events;
assert.ok(sessionEvents.some((event: { type: string; jobId?: string }) => event.type === "job.created" && event.jobId === sessionJob.json().jobId));
assert.equal((await app.inject({ method: "GET", url: `/api/jobs/${job.json().jobId}/diff` })).json().slides[0].available, false);
const diffStaging = await prepareStaging(root, path.join(root, "interaction"), job.json().jobId, ["P01"]);
await writeFile(path.join(diffStaging, "svg_output", "P01.svg"), '<svg xmlns="http://www.w3.org/2000/svg"><text id="title">Changed</text></svg>');
const diff = (await app.inject({ method: "GET", url: `/api/jobs/${job.json().jobId}/diff` })).json().slides[0];
assert.equal(diff.changed, true);
assert.notEqual(diff.beforeRevision, diff.afterRevision);
const regionJob = await app.inject({ method: "POST", url: "/api/jobs", payload: { scope: "region", targets: [{ slide: "P01", region: { x: 10, y: 20, width: 100, height: 50 } }], baseRevisions: { P01: slides.slides[0].revision }, intent: "重排区域内容", mode: "agent", exportAfter: false } });
assert.equal(regionJob.statusCode, 200);
assert.equal((await app.inject({ method: "GET", url: `/api/jobs/${regionJob.json().jobId}` })).json().plan.targets[0].region.width, 100);
assert.equal((await app.inject({ method: "POST", url: "/api/jobs", payload: { scope: "region", targets: [{ slide: "P01", region: { x: 10, y: 20, width: 0, height: 50 } }], baseRevisions: { P01: slides.slides[0].revision }, intent: "x", mode: "agent", exportAfter: false } })).statusCode, 422);
await writeFile(path.join(root, "svg_output", "P02.svg"), '<svg xmlns="http://www.w3.org/2000/svg"><text id="inside" x="10" y="10" width="30" height="20">In</text><text id="outside" x="300" y="300" width="30" height="20">Out</text></svg>');
const refreshedSlides = (await app.inject({ method: "GET", url: "/api/slides" })).json().slides;
const p02 = refreshedSlides.find((slide: { id: string }) => slide.id === "P02");
const guardedJob = await app.inject({ method: "POST", url: "/api/jobs", payload: { scope: "region", targets: [{ slide: "P02", region: { x: 0, y: 0, width: 100, height: 100 } }], baseRevisions: { P02: p02.revision }, intent: "direct region", mode: "direct", exportAfter: false } });
const outsideEdit = '<svg xmlns="http://www.w3.org/2000/svg"><text id="inside" x="10" y="10" width="30" height="20">Changed</text><text id="outside" x="300" y="300" width="30" height="20">Changed outside</text></svg>';
assert.equal((await app.inject({ method: "POST", url: `/api/jobs/${guardedJob.json().jobId}/run-direct`, payload: { slides: { P02: outsideEdit } } })).statusCode, 422);
assert.match(await readFile(path.join(root, "svg_output", "P02.svg"), "utf8"), />Out<\/text>/);
const p01BeforeBatch = await readFile(path.join(root, "svg_output", "P01.svg"), "utf8");
const p02BeforeBatch = await readFile(path.join(root, "svg_output", "P02.svg"), "utf8");
const batchSlides = (await app.inject({ method: "GET", url: "/api/slides" })).json().slides;
const batchRevisions = Object.fromEntries(batchSlides.map((slide: { id: string; revision: string }) => [slide.id, slide.revision]));
const batchJob = await app.inject({ method: "POST", url: "/api/jobs", payload: { scope: "pages", targets: [{ slide: "P01" }, { slide: "P02" }], baseRevisions: batchRevisions, intent: "批量直接修改", mode: "direct", exportAfter: false } });
await app.inject({ method: "POST", url: `/api/jobs/${batchJob.json().jobId}/approve` });
const unsafeBatch = await app.inject({ method: "POST", url: `/api/jobs/${batchJob.json().jobId}/run-direct`, payload: { slides: { P01: '<svg xmlns="http://www.w3.org/2000/svg"><text>Safe</text></svg>', P02: '<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>' } } });
assert.equal(unsafeBatch.statusCode, 422);
assert.equal(await readFile(path.join(root, "svg_output", "P01.svg"), "utf8"), p01BeforeBatch);
assert.equal(await readFile(path.join(root, "svg_output", "P02.svg"), "utf8"), p02BeforeBatch);
assert.equal((await app.inject({ method: "POST", url: "/api/jobs", payload: { scope: "page", targets: [{ slide: "P01" }], baseRevisions: { P01: `sha256:${"0".repeat(64)}` }, intent: "x", mode: "agent", exportAfter: false } })).statusCode, 409);
assert.equal((await app.inject({ method: "GET", url: "/api/events?since=0&stream=0" })).statusCode, 200);
const historyDirectory = path.join(root, "interaction", "revisions", "P01"); await mkdir(historyDirectory, { recursive: true });
const originalP01 = await readFile(path.join(root, "svg_output", "P01.svg"), "utf8");
await writeFile(path.join(historyDirectory, "9999999999999-history.svg"), '<svg xmlns="http://www.w3.org/2000/svg"><text id="title">Previous</text></svg>');
assert.equal((await app.inject({ method: "GET", url: "/api/slides/P01/history-state" })).json().canUndo, true);
assert.equal((await app.inject({ method: "POST", url: "/api/slides/P01/history/undo" })).json().operation, "undo");
assert.match(await readFile(path.join(root, "svg_output", "P01.svg"), "utf8"), /Previous/);
assert.equal((await app.inject({ method: "GET", url: "/api/slides/P01/history-state" })).json().canRedo, true);
assert.equal((await app.inject({ method: "POST", url: "/api/slides/P01/history/redo" })).json().operation, "redo");
assert.equal(await readFile(path.join(root, "svg_output", "P01.svg"), "utf8"), originalP01);
assert.equal((await app.inject({ method: "POST", url: "/api/slides/P01/history/redo" })).statusCode, 409);
assert.equal((await app.inject({ method: "POST", url: "/api/jobs/impact", payload: { scope: "deck", targets: [{ slide: "P01" }], baseRevisions: { P01: slides.slides[0].revision }, intent: "全局颜色调整", mode: "agent", exportAfter: false } })).json().requiresApproval, true);
const approval = await app.inject({ method: "POST", url: "/api/jobs", payload: { scope: "deck", targets: [{ slide: "P01" }], baseRevisions: { P01: slides.slides[0].revision }, intent: "全局颜色调整", mode: "agent", exportAfter: false } });
assert.equal(approval.json().status, "awaiting_approval");
assert.equal((await app.inject({ method: "POST", url: `/api/jobs/${approval.json().jobId}/run-agent`, payload: { provider: "codex" } })).statusCode, 409);
assert.equal((await app.inject({ method: "POST", url: `/api/jobs/${approval.json().jobId}/approve` })).statusCode, 200);
assert.equal((await app.inject({ method: "POST", url: `/api/jobs/${approval.json().jobId}/approve` })).statusCode, 409);
const candidate = await app.inject({ method: "POST", url: "/api/memory/candidates", payload: { trigger: "标题弱", lesson: "增强字号差" } });
assert.equal(candidate.statusCode, 200);
assert.equal((await app.inject({ method: "POST", url: `/api/memory/candidates/${candidate.json().candidateId}/accept` })).json().status, "accepted");
assert.equal((await app.inject({ method: "GET", url: "/api/memory/search?scope=project" })).json().memories.length, 1);
assert.equal((await app.inject({ method: "POST", url: `/api/memory/candidates/${candidate.json().candidateId}/withdraw` })).json().status, "withdrawn");
assert.equal((await app.inject({ method: "GET", url: "/api/memory/search?scope=project" })).json().memories.length, 0);
const rejected = await app.inject({ method: "POST", url: "/api/memory/candidates", payload: { trigger: "一次性事实", lesson: "不要复用" } });
await app.inject({ method: "PATCH", url: `/api/memory/candidates/${rejected.json().candidateId}`, payload: { lesson: "仍然不要复用" } });
await app.inject({ method: "POST", url: `/api/memory/candidates/${rejected.json().candidateId}/reject` });
assert.equal((await app.inject({ method: "GET", url: "/api/memory/search" })).json().memories.length, 0);
const exportRequest = await app.inject({ method: "POST", url: "/api/export" });
assert.equal((await app.inject({ method: "POST", url: "/api/export/result", payload: { status: "completed", deckRevision: exportRequest.json().deckRevision } })).statusCode, 200);
assert.deepEqual((await app.inject({ method: "GET", url: "/api/export/history" })).json().exports, []);
assert.equal((await app.inject({ method: "GET", url: "/api/export/history/export_missing/download" })).statusCode, 404);
await writeFile(path.join(root, "animations.json"), "{}", "utf8");
const beforeSidecar = (await app.inject({ method: "GET", url: "/api/project" })).json().deckRevision;
const openedSidecar = (await app.inject({ method: "GET", url: "/api/sidecar-content?name=animations.json" })).json();
assert.equal(openedSidecar.editable, true); assert.match(openedSidecar.revision, /^sha256:/);
const sidecarUpdate = await app.inject({ method: "PUT", url: "/api/sidecars/animations.json", payload: { content: '{"slides":[]}', revision: openedSidecar.revision } });
assert.notEqual(sidecarUpdate.json().deckRevision, beforeSidecar);
assert.equal((await app.inject({ method: "PUT", url: "/api/sidecars/animations.json", payload: { content: '{}', revision: openedSidecar.revision } })).statusCode, 409);
assert.equal((await app.inject({ method: "PUT", url: "/api/sidecars/animations.json", payload: { content: 'invalid' } })).statusCode, 422);
await writeFile(path.join(root, "interaction", "validation_report.json"), '{"status":"passed"}', "utf8");
const validationSidecar = (await app.inject({ method: "GET", url: "/api/sidecar-content?name=interaction%2Fvalidation_report.json" })).json();
assert.equal(validationSidecar.editable, false); assert.match(validationSidecar.content, /passed/);
assert.equal((await app.inject({ method: "GET", url: "/api/sidecar-content?name=notes" })).statusCode, 404);
const notesRoster = (await app.inject({ method: "GET", url: "/api/accessories/notes" })).json();
assert.equal((await app.inject({ method: "PUT", url: "/api/accessories/notes", payload: { notes: Object.fromEntries(notesRoster.roster.map((slide: string) => [slide, "本页讲稿"])) } })).statusCode, 200);
assert.equal((await app.inject({ method: "PUT", url: "/api/accessories/notes", payload: { notes: { ...notesRoster.notes, extra: "越界" } } })).statusCode, 422);
await app.close();

const generatingRoot = await mkdtemp(path.join(os.tmpdir(), "fastppt-generating-"));
await mkdir(path.join(generatingRoot, "svg_output"));
await mkdir(path.join(generatingRoot, "interaction"));
await writeFile(path.join(generatingRoot, "svg_output", "P01.svg"), "<svg/>");
await writeFile(path.join(generatingRoot, "interaction", "project_state.json"), JSON.stringify({ route: "generate-pptx", stage: "step6", editingReady: false }));
const generatingApp = await createStudio(generatingRoot);
const generatingSlides = (await generatingApp.inject({ method: "GET", url: "/api/slides" })).json().slides;
const waitingJob = await generatingApp.inject({ method: "POST", url: "/api/jobs", payload: { scope: "page", targets: [{ slide: "P01" }], baseRevisions: { P01: generatingSlides[0].revision }, intent: "生成后修改", mode: "agent", exportAfter: false } });
assert.equal(waitingJob.json().status, "waiting_workflow");
assert.equal((await generatingApp.inject({ method: "POST", url: `/api/jobs/${waitingJob.json().jobId}/run-agent`, payload: { provider: "codex" } })).statusCode, 409);
assert.deepEqual((await generatingApp.inject({ method: "POST", url: "/api/workflow/edits-ready" })).json().released, [waitingJob.json().jobId]);
assert.equal((await generatingApp.inject({ method: "POST", url: `/api/jobs/${waitingJob.json().jobId}/poll` })).json().status, "queued");
await generatingApp.close();

const recoveryRoot = await mkdtemp(path.join(os.tmpdir(), "fastppt-recovery-"));
await mkdir(path.join(recoveryRoot, "svg_output"));
await writeFile(path.join(recoveryRoot, "svg_output", "P01.svg"), "<svg>new</svg>");
const recoveryInteraction = path.join(recoveryRoot, "interaction");
const recoveryJob = path.join(recoveryInteraction, "jobs", "interrupted");
const recoveryBackup = path.join(recoveryInteraction, "revisions", "P01", "old.svg");
await mkdir(path.dirname(recoveryBackup), { recursive: true });
await mkdir(recoveryJob, { recursive: true });
await writeFile(recoveryBackup, "<svg>old</svg>");
await writeFile(path.join(recoveryJob, "commit.json"), JSON.stringify({ status: "started", slides: ["P01"], applied: ["P01"], backups: { P01: recoveryBackup } }));
assert.deepEqual(await recoverTransactions(recoveryRoot, recoveryInteraction), ["interrupted"]);
assert.equal(await readFile(path.join(recoveryRoot, "svg_output", "P01.svg"), "utf8"), "<svg>old</svg>");
const roundtrip = await mkdtemp(path.join(os.tmpdir(), "fastppt-roundtrip-"));
await mkdir(path.join(roundtrip, "authoring-svg-flat"));
await writeFile(path.join(roundtrip, "authoring-svg-flat", "slide_01.svg"), "<svg/>");
const roundtripApp = await createStudio(roundtrip);
assert.equal((await roundtripApp.inject({ method: "GET", url: "/api/slides" })).json().slides[0].id, "slide_01");
await roundtripApp.close();
const templateRoot = await mkdtemp(path.join(os.tmpdir(), "fastppt-template-"));
await mkdir(path.join(templateRoot, "interaction"));
await writeFile(path.join(templateRoot, "interaction", "project_state.json"), JSON.stringify({ route: "create-template", stage: "review" }));
const templateApp = await createStudio(templateRoot);
assert.equal((await templateApp.inject({ method: "GET", url: "/api/project" })).json().editingSupported, false);
assert.deepEqual((await templateApp.inject({ method: "GET", url: "/api/slides" })).json().slides, []);
assert.equal((await templateApp.inject({ method: "POST", url: "/api/jobs", payload: { scope: "page", targets: [{ slide: "P01" }], baseRevisions: { P01: `sha256:${"0".repeat(64)}` }, intent: "x", mode: "agent", exportAfter: false } })).statusCode, 409);
await templateApp.close();
const agentRoot = await mkdtemp(path.join(os.tmpdir(), "fastppt-agent-success-"));
await mkdir(path.join(agentRoot, "svg_output"));
await writeFile(path.join(agentRoot, "svg_output", "P01.svg"), '<svg xmlns="http://www.w3.org/2000/svg"><text id="title">Before</text></svg>');
const agentApp = await createStudio(agentRoot, {
  checker: async () => ({ code: 0, stdout: "passed", stderr: "" }),
  exporter: async () => ({ code: 0, status: "completed", receipt: { returncode: 0, deckRevision: "test" } }),
  agent: async (_provider, _prompt, stagingRoot) => { await writeFile(path.join(stagingRoot, "svg_output", "P01.svg"), '<svg xmlns="http://www.w3.org/2000/svg"><text id="title">After</text></svg>'); return "Validated title adjustment"; },
});
const agentSlide = (await agentApp.inject({ method: "GET", url: "/api/slides" })).json().slides[0];
const agentJob = await agentApp.inject({ method: "POST", url: "/api/jobs", payload: { scope: "page", targets: [{ slide: "P01" }], baseRevisions: { P01: agentSlide.revision }, intent: "change title", mode: "agent", exportAfter: true } });
const agentRun = await agentApp.inject({ method: "POST", url: `/api/jobs/${agentJob.json().jobId}/run-agent`, payload: { provider: "codex" } });
assert.equal(agentRun.statusCode, 200);
assert.equal(agentRun.json().status, "completed");
assert.equal(agentRun.json().memoryCandidate.status, "proposed");
const completedSession = (await agentApp.inject({ method: "GET", url: `/api/harness/sessions/${(await agentApp.inject({ method: "GET", url: `/api/jobs/${agentJob.json().jobId}` })).json().request.sessionId}` })).json();
assert.equal(completedSession.status, "idle");
assert.equal(completedSession.lastStatus, "completed");
assert.equal(completedSession.lastJobId, agentJob.json().jobId);
assert.match(await readFile(path.join(agentRoot, "svg_output", "P01.svg"), "utf8"), />After<\/text>/);
const agentEvents = (await agentApp.inject({ method: "GET", url: `/api/jobs/${agentJob.json().jobId}` })).json().events.map((event: { type: string }) => event.type);
for (const type of ["job.execution_started", "validation.started", "validation.passed", "revision.committed", "export.started", "memory.candidate_created", "job.completed"]) assert.ok(agentEvents.includes(type), type);
await agentApp.close();
const activeRecoveryRoot = await mkdtemp(path.join(os.tmpdir(), "fastppt-active-recovery-"));
await mkdir(path.join(activeRecoveryRoot, "svg_output"));
await mkdir(path.join(activeRecoveryRoot, "interaction", "jobs", "job_interrupted"), { recursive: true });
await mkdir(path.join(activeRecoveryRoot, "interaction", "sessions"), { recursive: true });
await writeFile(path.join(activeRecoveryRoot, "svg_output", "P01.svg"), "<svg/>");
await writeFile(path.join(activeRecoveryRoot, "interaction", "jobs", "job_interrupted", "request.json"), JSON.stringify({ jobId: "job_interrupted", status: "executing", sessionId: "session_interrupted" }));
await writeFile(path.join(activeRecoveryRoot, "interaction", "sessions", "session_interrupted.json"), JSON.stringify({ sessionId: "session_interrupted", kind: "codex", status: "running", activeJobId: "job_interrupted" }));
const recoveryApp = await createStudio(activeRecoveryRoot);
const recoveredJob = (await recoveryApp.inject({ method: "GET", url: "/api/jobs/job_interrupted" })).json().request;
assert.equal(recoveredJob.status, "failed");
assert.equal(recoveredJob.failure.layer, "recovery");
const recoveredSession = (await recoveryApp.inject({ method: "GET", url: "/api/harness/sessions/session_interrupted" })).json();
assert.equal(recoveredSession.status, "idle");
assert.equal(recoveredSession.recoveryReason, "studio_restart");
await recoveryApp.close();
const confirmRoot = await mkdtemp(path.join(os.tmpdir(), "fastppt-confirm-proxy-"));
await mkdir(path.join(confirmRoot, "svg_output"));
await writeFile(path.join(confirmRoot, "svg_output", "P01.svg"), "<svg/>");
const confirmServer = createServer((request, response) => {
  response.setHeader("content-type", "application/json");
  if (request.url === "/api/health") return response.end(JSON.stringify({ status: "ok", service: "confirm_ui", project: confirmRoot }));
  if (request.url === "/api/session") return response.end(JSON.stringify({ current_stage: "stage1" }));
  if (request.url === "/api/recommendations") return response.end(JSON.stringify({ stage: "stage1", recommend: { purpose: "test" } }));
  if (request.url === "/api/confirm" && request.method === "POST") return response.end(JSON.stringify({ stage: "stage1", status: "stage1-confirmed" }));
  response.statusCode = 404; response.end(JSON.stringify({ error: "missing" }));
});
await new Promise<void>((resolve) => confirmServer.listen(0, "127.0.0.1", resolve));
const confirmAddress = confirmServer.address();
assert.ok(confirmAddress && typeof confirmAddress !== "string");
await writeFile(path.join(confirmRoot, ".confirm_ui.lock"), JSON.stringify({ port: confirmAddress.port }));
const confirmApp = await createStudio(confirmRoot);
assert.equal((await confirmApp.inject({ method: "POST", url: "/api/workflow/plan", payload: { title: "Confirmed deck", audience: "Team", tone: "Clear", canvas: "ppt169", pages: [{ id: "P01", role: "title", title: "Opening" }] } })).statusCode, 200);
assert.equal((await confirmApp.inject({ method: "GET", url: "/api/workflow/confirm/session" })).json().current_stage, "stage1");
assert.equal((await confirmApp.inject({ method: "GET", url: "/api/workflow/confirm/recommendations" })).json().stage, "stage1");
assert.equal((await confirmApp.inject({ method: "POST", url: "/api/workflow/confirm", payload: { stage: "stage1" } })).json().status, "stage1-confirmed");
assert.equal((await confirmApp.inject({ method: "GET", url: "/api/workflow/plan" })).json().status, "confirmed");
const confirmedProject = (await confirmApp.inject({ method: "GET", url: "/api/project" })).json();
assert.equal(confirmedProject.stage, "generation");
assert.equal(confirmedProject.deckStatus, "ready");
await confirmApp.close();
await new Promise<void>((resolve, reject) => confirmServer.close((error) => error ? reject(error) : resolve()));
const fileRoot = await mkdtemp(path.join(os.tmpdir(), "fastppt-file-agent-"));
await mkdir(path.join(fileRoot, "svg_output"));
await writeFile(path.join(fileRoot, "svg_output", "P01.svg"), '<svg xmlns="http://www.w3.org/2000/svg"><text id="title">Before</text></svg>');
const fileApp = await createStudio(fileRoot, { checker: async () => ({ code: 0, stdout: "passed", stderr: "" }) });
const fileSlide = (await fileApp.inject({ method: "GET", url: "/api/slides" })).json().slides[0];
const fileJob = await fileApp.inject({ method: "POST", url: "/api/jobs", payload: { scope: "page", targets: [{ slide: "P01" }], baseRevisions: { P01: fileSlide.revision }, intent: "offline edit", mode: "agent", exportAfter: false } });
const handoff = (await fileApp.inject({ method: "POST", url: `/api/jobs/${fileJob.json().jobId}/file-handoff` })).json();
assert.equal(handoff.status, "waiting_agent");
await writeFile(path.join(handoff.stagingRoot, "svg_output", "P01.svg"), '<svg xmlns="http://www.w3.org/2000/svg"><text id="title">File agent</text></svg>');
await mkdir(path.dirname(handoff.responseFile), { recursive: true });
await writeFile(handoff.responseFile, JSON.stringify({ status: "completed", text: "offline result" }));
assert.equal((await fileApp.inject({ method: "POST", url: `/api/jobs/${fileJob.json().jobId}/file-response` })).json().provider, "file");
assert.match(await readFile(path.join(fileRoot, "svg_output", "P01.svg"), "utf8"), /File agent/);
await fileApp.close();
console.log("studio-ts e2e ok");
