// @ts-nocheck
import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { Activity, Archive, ArrowRight, Check, ChevronRight, FileText, ImagePlus, LayoutTemplate, LoaderCircle, Plus, RotateCcw, Settings2, Sparkles, TestTube2, Upload, X } from "lucide-react";
import { api, ApiError, artifactUrl, requestKey } from "./api/client";
import type { EntryMode, Page, Plan, Preflight, Project, ProviderProfile } from "./types";
import "./styles.css";

const entries: { id: EntryMode; label: string; detail: string; icon: typeof FileText }[] = [
  { id: "document_create", label: "文档生成", detail: "Markdown、TXT、DOCX 或 PDF", icon: FileText },
  { id: "page_entry", label: "逐页录入", detail: "逐页保留原文换行", icon: LayoutTemplate },
  { id: "pptx_improve", label: "改进已有 PPTX", detail: "重设计或高保真重建", icon: Upload },
];

const statusText: Record<string, string> = {
  awaiting_content_confirmation: "等待内容确认", awaiting_design_confirmation: "等待设计确认", generating_visuals: "视觉稿生成中",
  awaiting_representative_confirmation: "等待代表页确认", awaiting_visual_confirmation: "等待视觉审批", reconstructing: "可编辑重建中",
  completed: "已完成", cancelled: "已取消", failed: "需要处理", partial: "部分完成",
};

function App() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [selected, setSelected] = useState<Project | null>(null);
  const [entry, setEntry] = useState<EntryMode>("document_create");
  const [showAdmin, setShowAdmin] = useState(false);
  const [showTasks, setShowTasks] = useState(false);
  const [profiles, setProfiles] = useState<ProviderProfile[]>([]);
  const [profileDraft, setProfileDraft] = useState({ display_name: "", endpoint_mode: "relay", base_url: "", secret_reference: "env:FASTPPT_MODEL_API_KEY", capability_settings: '{"agent":{"backend":"codex","model":"gpt-5.2"},"image_generation":{"model":"gpt-image-2"},"image_edit":{"model":"gpt-image-2"}}' });
  const [newName, setNewName] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [showInput, setShowInput] = useState(false);
  const [inputText, setInputText] = useState("");
  const [inputFile, setInputFile] = useState<File | null>(null);
  const [busy, setBusy] = useState(false);
  const [flowStatus, setFlowStatus] = useState("");
  const [activePlan, setActivePlan] = useState<Plan | null>(null);
  const [pages, setPages] = useState<Page[]>([]);
  const [production, setProduction] = useState<Record<string, any>>({});
  const [jobs, setJobs] = useState<any[]>([]);
  const [agentRuns, setAgentRuns] = useState<any[]>([]);
  const [imageRuns, setImageRuns] = useState<any[]>([]);
  const [revisions, setRevisions] = useState<any[]>([]);
  const [preflight, setPreflight] = useState<Preflight | null>(null);
  const [design, setDesign] = useState({ contentMode: "strict_preserve", improvementMode: "redesign", representativePreflight: false, pageWidth: "13.333", pageHeight: "7.5", pageUnit: "inch", zhFont: "Microsoft YaHei", latinFont: "Arial" });

  const activeEntry = useMemo(() => entries.find((item) => item.id === entry)!, [entry]);

  async function refreshProjects() {
    try { const result = await api<{ projects: Project[] }>("/projects"); setProjects(result.projects); if (!selected && result.projects[0]) setSelected(result.projects[0]); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "无法加载项目"); }
    finally { setLoading(false); }
  }

  async function refreshFlow(projectId = selected?.project_id) {
    if (!projectId) return;
    try {
      const [pageResult, planResult, jobsResult, agentResult, imageResult, revisionResult] = await Promise.all([
        api<{ pages: Page[] }>(`/projects/${projectId}/pages`), api<{ plans: Plan[] }>(`/projects/${projectId}/plans`), api<{ jobs: any[] }>(`/projects/${projectId}/jobs`),
        api<{ agent_runs: any[] }>(`/projects/${projectId}/agent-runs`), api<{ image_runs: any[] }>(`/projects/${projectId}/image-runs`), api<{ deck_revisions: any[] }>(`/projects/${projectId}/deck-revisions`),
      ]);
      setPages(pageResult.pages || []); setJobs(jobsResult.jobs || []); setAgentRuns(agentResult.agent_runs || []); setImageRuns(imageResult.image_runs || []); setRevisions(revisionResult.deck_revisions || []);
      const latest = planResult.plans?.[0] || null;
      setActivePlan((current) => current && planResult.plans.some((item) => item.plan_id === current.plan_id) ? (planResult.plans.find((item) => item.plan_id === current.plan_id) || current) : latest);
      const states = await Promise.all((pageResult.pages || []).map(async (page) => { try { return [page.page_id, await api<any>(`/projects/${projectId}/pages/${page.page_id}/production-state`)] as const; } catch { return [page.page_id, null] as const; } }));
      setProduction(Object.fromEntries(states));
    } catch (reason) { setError(reason instanceof Error ? reason.message : "无法读取生产状态"); }
  }

  useEffect(() => { void refreshProjects(); }, []);
  useEffect(() => { setActivePlan(null); setPages([]); setProduction({}); if (selected) void refreshFlow(selected.project_id); }, [selected?.project_id]);
  useEffect(() => { if (!selected || !activePlan || !["generating_visuals", "reconstructing"].includes(activePlan.status)) return undefined; const timer = window.setInterval(() => void refreshFlow(selected.project_id), 1800); return () => window.clearInterval(timer); }, [selected?.project_id, activePlan?.status]);

  function showError(reason: unknown, fallback: string) { setError(reason instanceof ApiError ? reason.message : reason instanceof Error ? reason.message : fallback); }
  function openEntry() { if (!selected) return; setError(""); setFlowStatus(""); setInputText(""); setInputFile(null); setShowInput(true); }
  async function createProject() { if (!newName.trim()) return; try { const project = await api<Project>("/projects", { method: "POST", body: JSON.stringify({ name: newName.trim() }) }); setProjects((items) => [project, ...items]); setSelected(project); setNewName(""); } catch (reason) { showError(reason, "创建失败"); } }
  async function fileAsBase64(file: File) { const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ""; for (let index = 0; index < bytes.length; index += 0x8000) binary += String.fromCharCode(...bytes.subarray(index, index + 0x8000)); return btoa(binary); }
  function textAsBase64(value: string) { const bytes = new TextEncoder().encode(value); let binary = ""; for (let index = 0; index < bytes.length; index += 0x8000) binary += String.fromCharCode(...bytes.subarray(index, index + 0x8000)); return btoa(binary); }

  async function submitEntry() {
    if (!selected) return; setBusy(true); setError("");
    try {
      let sourceDocumentIds: string[] = [];
      if (entry !== "page_entry") { if (!inputFile && !inputText.trim()) throw new Error("请选择文件或粘贴文本"); const document = await api<{ document_id: string }>(`/projects/${selected.project_id}/documents`, { method: "POST", headers: { "Idempotency-Key": requestKey("document") }, body: JSON.stringify({ file_name: inputFile?.name || "pasted.txt", content_base64: inputFile ? await fileAsBase64(inputFile) : textAsBase64(inputText) }) }); sourceDocumentIds = [document.document_id]; }
      const session = await api<{ session_id: string }>(`/projects/${selected.project_id}/sessions`, { method: "POST", headers: { "Idempotency-Key": requestKey("session") }, body: JSON.stringify({ workflow_mode: entry, source_document_ids: sourceDocumentIds, options: { content_mode: design.contentMode, improvement_mode: design.improvementMode, representative_preflight: design.representativePreflight } }) });
      let pageDrafts: any[] | undefined;
      if (entry === "page_entry") { const chunks = inputText.split(/\r?\n\s*---+\s*\r?\n?/).map((chunk) => chunk.trim()).filter(Boolean); if (!chunks.length) throw new Error("请先输入至少一页内容"); pageDrafts = chunks.map((chunk, index) => { const [first, ...rest] = chunk.split(/\r?\n/); return { title: first.trim() || `第 ${index + 1} 页`, body: rest.join("\n").trim() || first.trim(), page_type: index === 0 ? "cover" : "content" }; }); }
      const plan = await api<Plan>(`/projects/${selected.project_id}/plans`, { method: "POST", headers: { "Idempotency-Key": requestKey("plan") }, body: JSON.stringify({ session_id: session.session_id, page_drafts: pageDrafts }) });
      setActivePlan(plan); setFlowStatus("内容计划已创建"); setShowInput(false); await refreshFlow(selected.project_id);
    } catch (reason) { showError(reason, "入口提交失败"); } finally { setBusy(false); }
  }

  async function confirmPlan() { if (!selected || !activePlan) return; setBusy(true); setError(""); try { const result = await api<Plan>(`/projects/${selected.project_id}/plans/${activePlan.plan_id}/confirm`, { method: "POST", headers: { "Idempotency-Key": requestKey("confirm-content") }, body: "{}" }); setActivePlan(result); setFlowStatus("内容已锁定，请确认设计参数"); } catch (reason) { showError(reason, "内容确认失败"); } finally { setBusy(false); } }
  async function confirmDesign() { if (!selected || !activePlan) return; setBusy(true); setError(""); try { const result = await api<Plan>(`/projects/${selected.project_id}/plans/${activePlan.plan_id}/design/confirm`, { method: "POST", headers: { "Idempotency-Key": requestKey("confirm-design") }, body: JSON.stringify({ representative_preflight: design.representativePreflight, page_size: { width: Number(design.pageWidth), height: Number(design.pageHeight), unit: design.pageUnit }, font_policy: { zh_family: design.zhFont, latin_family: design.latinFont } }) }); setActivePlan(result); setFlowStatus(result.status === "generating_visuals" ? "视觉稿已提交，等待任务完成" : "视觉稿已生成，请逐页审批"); await refreshFlow(selected.project_id); } catch (reason) { showError(reason, "设计确认失败"); } finally { setBusy(false); } }

  async function decideVisual(page: Page, decision: "approve" | "reject") { if (!selected || !page.visual_preview_artifact_id) return; setBusy(true); setError(""); try { const artifact = await api<any>(`/projects/${selected.project_id}/artifacts/${page.visual_preview_artifact_id}/metadata`); await api(`/projects/${selected.project_id}/pages/${page.page_id}/visual/${decision}`, { method: "POST", headers: { "Idempotency-Key": requestKey(`visual-${decision}`) }, body: JSON.stringify({ contract_revision: 1, visual_artifact_id: page.visual_preview_artifact_id, visual_sha256: artifact.sha256, comment: decision === "approve" ? "Web approval" : "Web rejection" }) }); setFlowStatus(decision === "approve" ? "视觉稿已批准" : "视觉稿已拒绝，请处理该页"); await refreshFlow(selected.project_id); } catch (reason) { showError(reason, "视觉审批失败"); } finally { setBusy(false); } }
  async function confirmSamples() { if (!selected || !activePlan) return; setBusy(true); setError(""); try { const result = await api<Plan>(`/projects/${selected.project_id}/plans/${activePlan.plan_id}/samples/confirm`, { method: "POST", headers: { "Idempotency-Key": requestKey("confirm-representatives") }, body: "{}" }); setActivePlan(result); setFlowStatus("代表页已确认，正在生成其余页面"); await refreshFlow(selected.project_id); } catch (reason) { showError(reason, "代表页确认失败"); } finally { setBusy(false); } }
  async function openPreflight(page: Page) { if (!selected) return; setBusy(true); setError(""); try { setPreflight(await api<Preflight>(`/projects/${selected.project_id}/pages/${page.page_id}/reconstruction/preflight`)); } catch (reason) { showError(reason, "无法读取重建披露"); } finally { setBusy(false); } }
  async function acceptPreflight() { if (!selected || !preflight) return; setBusy(true); setError(""); try { await api(`/projects/${selected.project_id}/pages/${preflight.page_id}/reconstruct`, { method: "POST", headers: { "Idempotency-Key": requestKey(`reconstruct-${preflight.page_id}`) }, body: JSON.stringify({ disclosure_sha256: preflight.disclosure_sha256, accept_wait_time: true, accept_supplier_fee_risk: true, accept_visual_difference: true, accept_editable_boundary: true, accepted_unsupported_object_ids: preflight.unsupported_items.map((item) => item.object_id) }) }); setPreflight(null); setFlowStatus("重建任务已提交"); await refreshFlow(selected.project_id); } catch (reason) { showError(reason, "重建提交失败"); } finally { setBusy(false); } }

  async function openAdmin() { setShowAdmin(true); setError(""); try { setProfiles((await api<{ profiles: ProviderProfile[] }>("/admin/provider-profiles")).profiles || []); } catch (reason) { showError(reason, "无法读取配置，请确认管理员会话"); } }
  async function createProfile() { setBusy(true); setError(""); try { const profile = await api<ProviderProfile>("/admin/provider-profiles", { method: "POST", headers: { "Idempotency-Key": requestKey("provider-profile") }, body: JSON.stringify({ display_name: profileDraft.display_name, endpoint_mode: profileDraft.endpoint_mode, base_url: profileDraft.endpoint_mode === "relay" ? profileDraft.base_url : undefined, secret_reference: profileDraft.secret_reference, capability_settings: JSON.parse(profileDraft.capability_settings) }) }); setProfiles((items) => [...items, profile]); setProfileDraft((draft) => ({ ...draft, display_name: "" })); } catch (reason) { showError(reason, "配置档案保存失败"); } finally { setBusy(false); } }
  async function profileAction(profileId: string, action: "test" | "archive" | "default") { setBusy(true); setError(""); try { const path = action === "test" ? `/admin/provider-profiles/${profileId}/test` : action === "default" ? `/admin/provider-profiles/${profileId}/default` : `/admin/provider-profiles/${profileId}`; const result = await api<any>(path, { method: action === "archive" ? "DELETE" : "POST", headers: { "Idempotency-Key": requestKey(`profile-${action}`) }, body: JSON.stringify({ capability: "agent" }) }); if (action === "test") setProfiles((items) => items.map((item) => item.profile_id === profileId ? result.profile : item)); else if (action === "archive") setProfiles((items) => items.filter((item) => item.profile_id !== profileId)); else setFlowStatus("默认 Agent 档案已更新"); } catch (reason) { showError(reason, "配置操作失败"); } finally { setBusy(false); } }

  const approvedCount = pages.filter((page) => production[page.page_id]?.visual_approval_id).length;
  const readyCount = pages.filter((page) => page.version_status === "ready" && page.svg_artifact_id).length;
  return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">F</span><span>FastPPT</span><small>工作台</small></div><div className="topbar-actions"><span className="save-state"><span className="status-dot" />状态已保存</span><button className="icon-button" title="管理员设置" aria-label="管理员设置" onClick={() => void openAdmin()}><Settings2 size={18} /></button></div></header>
    <main className="workspace"><aside className="sidebar" aria-label="演示项目导航"><div className="sidebar-heading"><span>演示项目</span><button className="icon-button" title="新建演示项目" aria-label="新建演示项目" onClick={() => document.getElementById("project-name")?.focus()}><Plus size={18} /></button></div><div className="project-create"><input id="project-name" value={newName} onChange={(event) => setNewName(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void createProject(); }} placeholder="新建演示项目" /><button className="create-button" onClick={() => void createProject()} aria-label="创建项目"><ArrowRight size={16} /></button></div><div className="project-list">{loading ? <div className="empty-state">正在读取项目…</div> : projects.length ? projects.map((project) => <button key={project.project_id} className={`project-item ${selected?.project_id === project.project_id ? "active" : ""}`} onClick={() => setSelected(project)}><span className="project-avatar">{project.name.slice(0, 1)}</span><span><strong>{project.name}</strong><small>{project.status === "draft" ? "草稿" : project.status}</small></span></button>) : <div className="empty-state">还没有演示项目</div>}</div></aside>
      <section className="content-area"><div className="content-header"><div><p className="eyebrow">演示项目</p><h1>{selected?.name || "创建第一份演示"}</h1><p className="muted">从输入、内容锁定到视觉审批和可编辑重建，所有状态都可以恢复。</p></div>{selected && <button className="secondary-button" onClick={() => setShowTasks(true)}><Activity size={16} />任务与版本</button>}</div>
        <div className="entry-grid">{entries.map(({ id, label, detail, icon: Icon }) => <button key={id} className={`entry-option ${entry === id ? "selected" : ""}`} onClick={() => setEntry(id)}><span className="entry-icon"><Icon size={20} /></span><span className="entry-copy"><strong>{label}</strong><small>{detail}</small></span>{entry === id && <Check className="entry-check" size={17} />}</button>)}</div>
        <div className="flow-band"><div className={`flow-step ${activePlan?.status === "awaiting_content_confirmation" ? "active" : ""}`}><span>01</span><strong>内容确认</strong></div><ChevronRight size={16} /><div className={`flow-step ${activePlan?.status === "awaiting_design_confirmation" ? "active" : ""}`}><span>02</span><strong>设计确认</strong></div><ChevronRight size={16} /><div className={`flow-step ${["awaiting_representative_confirmation", "awaiting_visual_confirmation", "generating_visuals"].includes(activePlan?.status) ? "active" : ""}`}><span>03</span><strong>视觉审批</strong></div><ChevronRight size={16} /><div className={`flow-step ${activePlan?.status === "completed" ? "active" : ""}`}><span>04</span><strong>可编辑重建</strong></div></div>
        <section className="start-panel"><div className="start-panel-icon"><Sparkles size={22} /></div><div><h2>{activePlan ? statusText[activePlan.status] || activePlan.status : activeEntry.label}</h2><p>{activePlan ? `计划 ${activePlan.plan_id} · ${activePlan.structured_plan?.pageDrafts?.length || pages.length || 0} 页` : activeEntry.detail}</p><div className="start-actions"><button className="primary-button" disabled={!selected || busy} onClick={openEntry}><Sparkles size={17} />开始{activeEntry.label}</button>{activePlan?.status === "awaiting_content_confirmation" && <button className="secondary-button" disabled={busy} onClick={() => void confirmPlan()}><Check size={16} />确认内容计划</button>}{activePlan?.status === "awaiting_design_confirmation" && <button className="secondary-button" disabled={busy} onClick={() => void confirmDesign()}><Check size={16} />确认设计并生成视觉稿</button>}{activePlan?.status === "awaiting_representative_confirmation" && <button className="secondary-button" disabled={busy} onClick={() => void confirmSamples()}><Check size={16} />确认代表页</button>}</div>{flowStatus && <div className="flow-status" role="status">{flowStatus}</div>}</div></section>
        {activePlan?.status === "awaiting_design_confirmation" && <section className="settings-strip"><div><strong>生产参数</strong><small>这些参数会写入页面合同</small></div><label>内容模式<select value={design.contentMode} onChange={(event) => setDesign({ ...design, contentMode: event.target.value })}><option value="strict_preserve">严格保留</option><option value="assisted">辅助整理</option></select></label><label>改进模式<select value={design.improvementMode} onChange={(event) => setDesign({ ...design, improvementMode: event.target.value })}><option value="redesign">默认重设计</option><option value="high_fidelity">高保真</option></select></label><label className="check-label"><input type="checkbox" checked={design.representativePreflight} onChange={(event) => setDesign({ ...design, representativePreflight: event.target.checked })} />主动预检代表页</label><label>页面尺寸<input value={`${design.pageWidth} x ${design.pageHeight}`} onChange={(event) => { const [width, height] = event.target.value.split("x").map((item) => item.trim()); setDesign({ ...design, pageWidth: width || design.pageWidth, pageHeight: height || design.pageHeight }); }} /></label></section>}
        {pages.length > 0 && <section className="gallery-section"><div className="section-heading"><div><p className="eyebrow">视觉画廊</p><h2>{approvedCount}/{pages.length} 页已审批 · {readyCount}/{pages.length} 页可编辑</h2></div><button className="text-button" onClick={() => selected && void refreshFlow(selected.project_id)}><RotateCcw size={15} />刷新</button></div><div className="visual-grid">{pages.map((page) => { const state = production[page.page_id] || {}; const approved = Boolean(state.visual_approval_id); const ready = page.version_status === "ready" && Boolean(page.svg_artifact_id); return <article className="visual-card" key={page.page_id}><div className="visual-frame">{page.visual_preview_artifact_id && selected && <img src={artifactUrl(selected.project_id, page.visual_preview_artifact_id)} alt={`第 ${page.order_index + 1} 页视觉稿`} />}</div><div className="visual-meta"><div><strong>第 {page.order_index + 1} 页 · {page.page_type}</strong><small>{ready ? "可编辑" : approved ? "视觉已批准" : page.version_status}</small></div>{approved ? <Check size={17} className="approved-icon" /> : <span className="status-dot" />}</div><div className="visual-actions">{!approved && page.visual_preview_artifact_id && <><button className="secondary-button" disabled={busy} onClick={() => void decideVisual(page, "approve")}><Check size={14} />批准</button><button className="text-button" disabled={busy} onClick={() => void decideVisual(page, "reject")}><X size={14} />拒绝</button></>}{approved && !ready && <button className="secondary-button" disabled={busy} onClick={() => void openPreflight(page)}><ArrowRight size={14} />重建前检查</button>}{ready && <span className="ready-label">Ready</span>}</div></article>; })}</div></section>}
        {error && <div className="error-banner" role="alert"><X size={16} />{error}<button onClick={() => setError("")} aria-label="关闭错误"><X size={15} /></button></div>}
      </section></main>
    {showAdmin && <div className="modal-backdrop" role="presentation" onClick={() => !busy && setShowAdmin(false)}><section className="admin-panel" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><div className="panel-heading"><div><p className="eyebrow">管理员</p><h2>连接配置档案</h2></div><button className="icon-button" title="关闭" aria-label="关闭" onClick={() => setShowAdmin(false)}><X size={18} /></button></div><p className="muted">浏览器只提交 Secret 引用，服务端负责解析和审计。</p><div className="profile-list">{profiles.length ? profiles.map((profile) => <div className="profile-row" key={profile.profile_id}><div><strong>{profile.display_name}</strong><small>{profile.endpoint_mode === "relay" ? "中转站" : "官方站"} · Agent {profile.connection_status_by_capability?.agent || "untested"}</small></div><div className="profile-actions"><span className={`status-pill ${profile.enabled ? "ready" : "disabled"}`}>{profile.enabled ? "启用" : "已归档"}</span>{profile.enabled && <><button className="icon-button" title="测试 Agent 连接" aria-label="测试 Agent 连接" onClick={() => void profileAction(profile.profile_id, "test")}><TestTube2 size={15} /></button><button className="icon-button" title="设为默认 Agent" aria-label="设为默认 Agent" onClick={() => void profileAction(profile.profile_id, "default")}><Check size={15} /></button><button className="icon-button" title="归档档案" aria-label="归档档案" onClick={() => void profileAction(profile.profile_id, "archive")}><Archive size={15} /></button></>}</div></div>) : <div className="empty-state">暂无配置档案</div>}</div><div className="profile-form"><input placeholder="档案名称" value={profileDraft.display_name} onChange={(event) => setProfileDraft({ ...profileDraft, display_name: event.target.value })} /><select value={profileDraft.endpoint_mode} onChange={(event) => setProfileDraft({ ...profileDraft, endpoint_mode: event.target.value })}><option value="relay">中转站</option><option value="official">官方站</option></select>{profileDraft.endpoint_mode === "relay" && <input placeholder="HTTPS Base URL" value={profileDraft.base_url} onChange={(event) => setProfileDraft({ ...profileDraft, base_url: event.target.value })} />}<input placeholder="Secret 引用，如 env:FASTPPT_MODEL_API_KEY" value={profileDraft.secret_reference} onChange={(event) => setProfileDraft({ ...profileDraft, secret_reference: event.target.value })} /><textarea value={profileDraft.capability_settings} onChange={(event) => setProfileDraft({ ...profileDraft, capability_settings: event.target.value })} rows={5} /><button className="primary-button" disabled={busy || !profileDraft.display_name.trim()} onClick={() => void createProfile()}><Plus size={15} />保存档案</button></div><div className="diagnostic-line"><ImagePlus size={16} />Agent、文生图和图像编辑能力分别测试。</div></section></div>}
    {showTasks && <div className="modal-backdrop" role="presentation" onClick={() => setShowTasks(false)}><section className="admin-panel" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><div className="panel-heading"><div><p className="eyebrow">运行记录</p><h2>任务与版本</h2></div><button className="icon-button" title="关闭" aria-label="关闭" onClick={() => setShowTasks(false)}><X size={18} /></button></div><div className="task-summary"><span><strong>{jobs.filter((job) => job.status === "queued" || job.status === "running").length}</strong>进行中</span><span><strong>{agentRuns.length}</strong> AgentRun</span><span><strong>{imageRuns.length}</strong> ImageRun</span><span><strong>{revisions.length}</strong> DeckRevision</span></div><div className="task-list">{jobs.slice(-8).reverse().map((job) => <div className="task-row" key={job.job_id}><LoaderCircle size={15} className={job.status === "running" ? "spin" : ""} /><span><strong>{job.kind}</strong><small>{job.status} · {job.job_id}</small></span></div>)}</div></section></div>}
    {showInput && <div className="modal-backdrop" role="presentation" onClick={() => !busy && setShowInput(false)}><section className="admin-panel input-panel" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><div className="panel-heading"><div><p className="eyebrow">{activeEntry.label}</p><h2>准备输入</h2></div><button className="icon-button" title="关闭" aria-label="关闭" onClick={() => setShowInput(false)}><X size={18} /></button></div>{entry === "page_entry" ? <textarea className="input-textarea" value={inputText} onChange={(event) => setInputText(event.target.value)} placeholder="标题\n正文\n---\n下一页标题\n正文" rows={12} /> : <><label className="file-picker"><Upload size={17} />{inputFile?.name || "选择资料文件"}<input type="file" accept=".md,.markdown,.txt,.docx,.pdf,.pptx" onChange={(event) => setInputFile(event.target.files?.[0] || null)} /></label><textarea className="input-textarea" value={inputText} onChange={(event) => setInputText(event.target.value)} placeholder="或者粘贴资料文本" rows={8} /></>}<div className="start-actions"><button className="primary-button" disabled={busy} onClick={() => void submitEntry()}><ArrowRight size={17} />{busy ? "提交中…" : "创建内容计划"}</button></div></section></div>}
    {preflight && <div className="modal-backdrop" role="presentation" onClick={() => !busy && setPreflight(null)}><section className="admin-panel disclosure-panel" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><div className="panel-heading"><div><p className="eyebrow">重建前检查</p><h2>第 {preflight.page_id} 页</h2></div><button className="icon-button" title="关闭" aria-label="关闭" onClick={() => setPreflight(null)}><X size={18} /></button></div><div className="disclosure-grid"><span>预计等待<strong>{preflight.estimated_wait_seconds} 秒</strong></span><span>Agent 调用<strong>{preflight.estimated_agent_calls}</strong></span><span>图片调用<strong>{preflight.estimated_image_calls}</strong></span><span>供应商费用风险<strong>{preflight.supplier_fee_risk ? "有" : "无"}</strong></span></div><p className="muted">{preflight.visual_difference_risk}</p><p className="muted">{preflight.editable_boundary}</p>{preflight.unsupported_items.length > 0 && <div className="warning-box">有 {preflight.unsupported_items.length} 个来源对象需要登记为不可编辑区域。</div>}<button className="primary-button" disabled={busy} onClick={() => void acceptPreflight()}><Check size={16} />同意披露并提交重建</button></section></div>}
  </div>;
}

export default App;

createRoot(document.getElementById("root")!).render(<App />);
