import React, { useState } from "react";
import "./IntakeComposer.css";

type Intake = { status: string; sessionId: string; sources?: string[]; pages?: unknown[] };

export function IntakeComposer({ provider = "codex", initialTopic = "", initialSources = [], onStatus, onCreated }: { provider?: string; initialTopic?: string; initialSources?: string[]; onStatus: (value: string) => void; onCreated: (intake: Intake) => void }) {
  const [topic, setTopic] = useState(initialTopic), [sources, setSources] = useState(initialSources.join("\n")), [busy, setBusy] = useState(false);
  const upload = async (files: FileList | null) => { if (!files?.length) return; setBusy(true); try { const uploaded: string[] = []; for (const file of Array.from(files)) { if (file.size > 20 * 1024 * 1024) throw new Error(`${file.name} 超过 20 MB`); const content = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(reader.error); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.readAsDataURL(file); }); const response = await fetch("/api/uploads", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: file.name, content }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? `上传失败 (${response.status})`); uploaded.push(body.source); } setSources((current) => [current.trim(), ...uploaded].filter(Boolean).join("\n")); onStatus(`已上传 ${uploaded.length} 个素材`); } catch (error) { onStatus(`上传失败 · ${(error as Error).message}`); } finally { setBusy(false); } };
  const submit = async () => { if (!topic.trim()) return onStatus("请输入演示主题"); setBusy(true); try { const sourcePaths = sources.split(/\r?\n/).map((value) => value.trim()).filter(Boolean); const response = await fetch("/api/workflow/intake", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ topic, provider, sources: sourcePaths }) }); let body = await response.json(); if (!response.ok) throw new Error(body.error ?? `请求失败 (${response.status})`); if (!sourcePaths.length) { onStatus("正在检索权威来源并整理事实…"); const researched = await fetch("/api/workflow/research/run", { method: "POST" }); body = await researched.json(); if (!researched.ok) throw new Error(body.error ?? `主题研究失败 (${researched.status})`); } onStatus("正在转换并导入素材…"); const imported = await fetch("/api/workflow/intake/import", { method: "POST" }); body = await imported.json(); if (!imported.ok) throw new Error(body.error ?? body.stderr ?? `素材导入失败 (${imported.status})`); onStatus("素材与研究事实已就绪，正在生成规划…"); const planned = await fetch("/api/workflow/plan/run", { method: "POST" }); body = await planned.json(); if (!planned.ok) throw new Error(body.error ?? `规划失败 (${planned.status})`); onCreated(body); window.dispatchEvent(new CustomEvent("studio:plan-ready", { detail: body })); onStatus(`规划已生成 · ${body.pages?.length ?? 0} 页`); } catch (error) { onStatus(`启动失败 · ${(error as Error).message}`); } finally { setBusy(false); } };
  return <section className="intake-composer"><b>创建演示文稿</b><p>输入主题，可上传素材或填写当前项目内的相对路径。</p><textarea value={topic} onChange={(event) => setTopic(event.target.value)} placeholder="例如：面向本科生的人工智能导论课程"/><label className="upload-button">上传素材<input type="file" multiple accept=".md,.txt,.pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.csv,.json,.png,.jpg,.jpeg,.webp,.svg" disabled={busy} onChange={(event) => void upload(event.target.files)}/></label><textarea className="source-list" value={sources} onChange={(event) => setSources(event.target.value)} placeholder={"uploads/brief.md\nsources/paper.pdf"}/><button className="primary" disabled={busy || !topic.trim()} onClick={submit}>{busy ? "正在处理…" : "生成规划"}</button></section>;
}
