import React, { useEffect, useState } from "react";
import "./PlanningEditor.css";
type PagePlan = { id: string; role: string; title: string };
type Plan = { title: string; audience: string; tone: string; canvas: string; pageCount?: string; visualStyle?: string; colorDirection?: string; themeColor?: string; template?: string; pages: PagePlan[] };
async function request<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(url, options); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? `请求失败 (${response.status})`); return body; }
export function PlanningEditor({ onStatus }: { onStatus: (value: string) => void }) {
  const [plan, setPlan] = useState<Plan | null>(), [busy, setBusy] = useState(false), [dirty, setDirty] = useState(false);
  useEffect(() => { request<Plan>("/api/workflow/plan").then(setPlan, () => setPlan(null)); }, []);
  if (plan === undefined) return <div className="cards"><article>正在加载规划…</article></div>;
  if (plan === null) return <div className="cards"><article className="empty"><b>暂无规划</b><p>主题研究与规划完成后，可在这里调整页面顺序、角色和标题。</p></article></div>;
  const update = (next: Plan) => { setPlan(next); setDirty(true); };
  const updatePage = (index: number, key: keyof PagePlan, value: string) => update({ ...plan, pages: plan.pages.map((page, pageIndex) => pageIndex === index ? { ...page, [key]: value } : page) });
  const move = (index: number, offset: number) => { const target = index + offset; if (target < 0 || target >= plan.pages.length) return; const pages = [...plan.pages]; [pages[index], pages[target]] = [pages[target], pages[index]]; update({ ...plan, pages }); };
  const addPage = () => { const used = new Set(plan.pages.map((page) => page.id)); let number = plan.pages.length + 1; while (used.has(`P${String(number).padStart(2, "0")}`)) number += 1; update({ ...plan, pages: [...plan.pages, { id: `P${String(number).padStart(2, "0")}`, role: "content", title: "新页面" }] }); };
  const removePage = (index: number) => { if (plan.pages.length === 1) return onStatus("规划必须保留至少一页"); update({ ...plan, pages: plan.pages.filter((_, pageIndex) => pageIndex !== index) }); };
  const save = async () => { setBusy(true); try { setPlan(await request<Plan>("/api/workflow/plan", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(plan) })); setDirty(false); onStatus("规划已保存，等待确认"); } catch (error) { onStatus(`规划保存失败 · ${(error as Error).message}`); } finally { setBusy(false); } };
  return <div className="planning"><div className="planning-heading"><b>结构化规划</b><small>{dirty ? "有未保存更改" : `${plan.pages.length} 页`}</small></div><label>标题<input value={plan.title} onChange={(event) => update({ ...plan, title: event.target.value })}/></label><label>页数<input value={plan.pageCount ?? String(plan.pages.length)} onChange={(event) => update({ ...plan, pageCount: event.target.value })}/></label><label>风格<input value={plan.visualStyle ?? ""} onChange={(event) => update({ ...plan, visualStyle: event.target.value })}/></label><label>色彩方向<input value={plan.colorDirection ?? ""} onChange={(event) => update({ ...plan, colorDirection: event.target.value })}/></label><label>受众<input value={plan.audience} onChange={(event) => update({ ...plan, audience: event.target.value })}/></label><label>语气<input value={plan.tone} onChange={(event) => update({ ...plan, tone: event.target.value })}/></label><label>画布<input value={plan.canvas} onChange={(event) => update({ ...plan, canvas: event.target.value })}/></label><label>主题色<input aria-label="主题色" type="color" value={plan.themeColor ?? "#356ac4"} onChange={(event) => update({ ...plan, themeColor: event.target.value })}/></label><label>模板（可选）<input value={plan.template ?? ""} placeholder="自由设计或模板工作区" onChange={(event) => update({ ...plan, template: event.target.value || undefined })}/></label><div className="planning-pages">{plan.pages.map((page, index) => <article key={page.id}><b>{page.id}</b><input aria-label={`${page.id} 角色`} value={page.role} onChange={(event) => updatePage(index, "role", event.target.value)}/><input aria-label={`${page.id} 标题`} value={page.title} onChange={(event) => updatePage(index, "title", event.target.value)}/><div><button disabled={index === 0} onClick={() => move(index, -1)}>↑</button><button disabled={index === plan.pages.length - 1} onClick={() => move(index, 1)}>↓</button><button aria-label={`删除 ${page.id}`} onClick={() => removePage(index)}>×</button></div></article>)}</div><div className="planning-actions"><button onClick={addPage}>新增页面</button><button className="primary" disabled={busy || !dirty} onClick={save}>{busy ? "保存中…" : "保存规划"}</button></div></div>;
}
