import { themeDecorPath, themePhotoPath } from './theme-assets.mjs'

const PHOTO_DECOR_SIZES = Object.freeze([
  { cols: [4, 6], rows: [4, 6], ratio: [0.85, 1.2] },
  { cols: [5, 12], rows: [3, 8], ratio: [1.15, 4] },
])

/**
 * @param {number} number
 * @param {string[]} meanings
 * @param {string[]} tones
 * @param {Partial<import('./image-config.mjs').ImageDataInput>} [image]
 */
function photoDecor(number, meanings, tones, image = {}) {
  return {
    id: `decor-photo-${String(number).padStart(2, '0')}`,
    src: themePhotoPath(number),
    sizes: PHOTO_DECOR_SIZES,
    meanings: ['photo', ...meanings],
    tones,
    image: {
      fit: 'cover',
      position: 'center',
      zoom: 1,
      ...image,
    },
  }
}

export const DEFAULT_DECOR_DATA = Object.freeze([
  {
    id: 'decor-cover-band-01',
    src: themeDecorPath('decor-1.svg'),
    sizes: [{ cols: [3, 8], rows: [2, 5], ratio: [1, 1.5] }],
    meanings: ['cover', 'hero', 'course'],
    tones: ['green', 'orange', 'blue'],
    image: {
      fit: 'contain',
      position: 'center',
      zoom: 1.05,
    },
  },
  {
    id: 'decor-support-raster-01',
    src: themeDecorPath('decor-2.png'),
    sizes: [{ cols: [2, 6], rows: [2, 6], ratio: [0.75, 1.2] }],
    meanings: ['support', 'media'],
    tones: ['orange', 'light', 'warm'],
    image: {
      fit: 'scale-down',
      position: '100% 50%',
      anchor: 'right center',
      backgroundColor: '#f5f5f5',
    },
  },
  {
    id: 'decor-square-orbit-01',
    src: themeDecorPath('decor-3.svg'),
    sizes: [{ cols: [3, 5], rows: [3, 5], ratio: [0.8, 1.25] }],
    meanings: ['qa', 'testing', 'practice'],
    tones: ['blue', 'orange', 'green'],
    image: {
      fit: 'contain',
      position: 'center',
      zoom: 1.06,
    },
  },
  {
    id: 'decor-support-wide-01',
    src: themeDecorPath('decor-4.svg'),
    sizes: [{ cols: [4, 8], rows: [2, 8], ratio: [1, 4] }],
    meanings: ['support', 'learning'],
    tones: ['green', 'blue', 'orange'],
    image: {
      fit: 'fill',
      position: '50% 50%',
      zoom: 0.9,
    },
  },
  {
    id: 'decor-support-raster-02',
    src: themeDecorPath('decor-5.png'),
    sizes: [
      { cols: 6, rows: 5 },
      { cols: 6, rows: 6 },
      { cols: 7, rows: 6 },
      { cols: 7, rows: 7 },
    ],
    meanings: ['support', 'media'],
    tones: ['orange', 'warm'],
    image: {
      fit: 'cover',
      position: '0% 0%',
      anchor: 'right top',
      x: '-15%',
      y: '26.5%',
      backgroundColor: 'var(--theme-color-orange-1)',
    },
  },
  {
    id: 'decor-support-raster-03',
    src: themeDecorPath('decor-6.png'),
    sizes: [{ cols: [3, 5], rows: [3, 5], ratio: [0.8, 1.25] }],
    meanings: ['support', 'media'],
    tones: ['orange', 'warm'],
    image: {
      fit: 'contain',
      position: '50% 50%',
      backgroundColor: 'var(--theme-color-orange-0)',
    },
  },
  {
    id: 'decor-media-square-01',
    src: themeDecorPath('decor-7.png'),
    sizes: [{ cols: [3, 5], rows: [3, 5], ratio: [0.8, 1.25] }],
    meanings: ['media', 'practice', 'support'],
    tones: ['blue', 'orange', 'green'],
    image: {
      fit: 'contain',
      position: '50% 50%',
      zoom: 0.9,
      backgroundColor: 'var(--theme-color-blue-1)',
    },
  },
  {
    id: 'decor-cover-vertical-01',
    src: themeDecorPath('decor-8.svg'),
    sizes: [{ cols: [2, 4], rows: [3, 8], ratio: [0.25, 0.95] }],
    meanings: ['cover', 'hero', 'course'],
    tones: ['orange', 'green', 'blue'],
    image: {
      fit: 'contain',
      position: 'center',
      zoom: 1.08,
    },
  },
  {
    id: 'decor-cover-ribbon-01',
    src: themeDecorPath('decor-9.svg'),
    sizes: [{ cols: [4, 8], rows: [2, 4], ratio: [1.4, 4] }],
    meanings: ['cover', 'hero', 'support'],
    tones: ['orange', 'blue', 'green'],
    image: {
      fit: 'contain',
      position: '50% 70%',
      zoom: 1.7,
    },
  },
  {
    id: 'decor-rules-wide-01',
    src: themeDecorPath('decor-10.svg'),
    sizes: [{ cols: [4, 12], rows: [3, 6], ratio: [1.4, 4] }],
    meanings: ['rules', 'webinar', 'qa'],
    tones: ['green', 'dark', 'blue', 'orange'],
    image: {
      fit: 'contain',
      position: 'left top',
      anchor: 'left top',
      x: '50%',
      y: '12%',
      zoom: 3,
      color: 'var(--theme-color-dark-0)',
      opacity: 1,
    },
  },
  {
    id: 'decor-agenda-tall-01',
    src: themeDecorPath('decor-11.svg'),
    sizes: [{ cols: [3, 4], rows: [8, 12], ratio: [0.25, 0.55] }],
    meanings: ['agenda', 'toc'],
    tones: ['blue', 'orange', 'green', 'dark'],
    image: {
      fit: 'contain',
      position: 'right center',
      zoom: 1,
      opacity: 0.85,
    },
  },
  {
    id: 'decor-signal-tall-01',
    src: themeDecorPath('decor-12.svg'),
    sizes: [{ cols: [2, 4], rows: [4, 12], ratio: [0.2, 0.8] }],
    meanings: ['signal', 'cover', 'hero'],
    tones: ['blue', 'orange', 'green'],
    image: {
      fit: 'cover',
      position: '50% 50%',
      zoom: 2,
    },
  },
  {
    id: 'decor-support-compact-01',
    src: themeDecorPath('decor-13.svg'),
    sizes: [{ cols: [2, 6], rows: [2, 6], ratio: [0.75, 1.35] }],
    meanings: ['support', 'practice'],
    tones: ['green', 'blue', 'orange'],
    image: {
      fit: 'contain',
      position: '50% 50%',
      zoom: 0.9,
    },
  },
  {
    id: 'decor-panel-vertical-01',
    src: themeDecorPath('decor-14.svg'),
    sizes: [{ cols: [3, 5], rows: [4, 7], ratio: [0.45, 0.95] }],
    meanings: ['support', 'rules', 'qa'],
    tones: ['orange', 'blue', 'green'],
    image: {
      fit: 'contain',
      position: '100% 50%',
      anchor: 'right center',
      x: '3%',
      zoom: 0.9,
    },
  },
  {
    id: 'decor-support-wide-02',
    src: themeDecorPath('decor-15.svg'),
    sizes: [{ cols: [4, 8], rows: [2, 5], ratio: [1.2, 4] }],
    meanings: ['support', 'learning'],
    tones: ['orange', 'green', 'blue'],
    image: {
      fit: 'contain',
      position: 'center',
      zoom: 1,
    },
  },
  {
    id: 'decor-support-wide-03',
    src: themeDecorPath('decor-16.svg'),
    sizes: [{ cols: [5, 9], rows: [2, 4], ratio: [1.4, 4.5] }],
    meanings: ['support', 'learning'],
    tones: ['blue', 'green', 'orange'],
    image: {
      fit: 'contain',
      position: 'center',
      zoom: 1,
    },
  },
  {
    id: 'decor-media-square-02',
    src: themeDecorPath('decor-17.png'),
    sizes: [{ cols: [3, 5], rows: [3, 5], ratio: [0.8, 1.25] }],
    meanings: ['media', 'support'],
    tones: ['green', 'orange', 'blue'],
    image: {
      fit: 'contain',
      position: '50% 50%',
      zoom: 0.9,
      backgroundColor: 'var(--theme-color-light-1)',
    },
  },
  {
    id: 'decor-media-square-03',
    src: themeDecorPath('decor-18.png'),
    sizes: [{ cols: [3, 6], rows: [3, 6], ratio: [0.75, 1.35] }],
    meanings: ['media', 'support'],
    tones: ['orange', 'blue', 'green'],
    image: {
      fit: 'cover',
      position: '50% 46%',
      x: '-25.5%',
      zoom: 1.6,
      backgroundColor: 'var(--theme-color-dark-1)',
    },
  },
  {
    id: 'decor-support-tall-01',
    src: themeDecorPath('decor-19.svg'),
    sizes: [{ cols: [3, 5], rows: [3, 9], ratio: [0.35, 1.1] }],
    meanings: ['support', 'practice'],
    tones: ['blue', 'orange', 'green'],
    image: {
      fit: 'cover',
      position: '50% 50%',
    },
  },
  photoDecor(
    1,
    ['portrait', 'workspace', 'home', 'learning'],
    ['orange', 'yellow', 'light', 'neutral', 'warm'],
    { position: '50% 44%', zoom: 1.06 },
  ),
  photoDecor(
    2,
    ['portrait', 'workspace', 'outdoor', 'learning'],
    ['orange', 'blue', 'green', 'yellow', 'warm'],
    { position: '50% 42%', zoom: 1.06 },
  ),
  photoDecor(
    3,
    ['portrait', 'workspace', 'office', 'learning'],
    ['orange', 'yellow', 'dark', 'warm', 'neutral'],
    { position: '50% 44%', zoom: 1.04 },
  ),
  photoDecor(
    4,
    ['portrait', 'transit', 'workspace', 'learning'],
    ['blue', 'green', 'light', 'yellow', 'cool'],
    { position: '42% 42%', zoom: 1.06 },
  ),
  photoDecor(
    5,
    ['portrait', 'workshop', 'outdoor', 'learning'],
    ['blue', 'dark', 'cool', 'neutral'],
    { position: '50% 40%', zoom: 1.08 },
  ),
  photoDecor(
    6,
    ['portrait', 'workspace', 'home', 'learning'],
    ['blue', 'dark', 'cool', 'neutral'],
    { position: '50% 44%', zoom: 1.04 },
  ),
  photoDecor(
    7,
    ['portrait', 'workspace', 'outdoor', 'learning'],
    ['green', 'yellow', 'neutral', 'warm'],
    { position: '50% 45%', zoom: 1.04 },
  ),
  photoDecor(
    8,
    ['workspace', 'programming', 'home', 'learning'],
    ['orange', 'yellow', 'light', 'neutral', 'warm'],
    { position: '50% 44%', zoom: 1.02 },
  ),
  photoDecor(
    9,
    ['portrait', 'workspace', 'learning'],
    ['orange', 'yellow', 'light', 'neutral', 'warm'],
    { position: '50% 44%', zoom: 1.05 },
  ),
  photoDecor(
    10,
    ['portrait', 'outdoor', 'mobile', 'learning'],
    ['orange', 'green', 'yellow', 'warm', 'neutral'],
    { position: '50% 44%', zoom: 1.05 },
  ),
  photoDecor(
    11,
    ['portrait', 'outdoor', 'mobile', 'learning'],
    ['blue', 'dark', 'cool', 'neutral'],
    { position: '50% 42%', zoom: 1.06 },
  ),
  photoDecor(
    12,
    ['portrait', 'outdoor', 'mobile', 'learning'],
    ['green', 'blue', 'yellow', 'cool', 'neutral'],
    { position: '50% 44%', zoom: 1.06 },
  ),
  photoDecor(
    13,
    ['portrait', 'outdoor', 'mobile', 'learning'],
    ['blue', 'light', 'cool', 'neutral'],
    { position: '50% 43%', zoom: 1.06 },
  ),
  photoDecor(
    14,
    ['portrait', 'outdoor', 'hero'],
    ['blue', 'green', 'light', 'cool', 'neutral'],
    { position: '50% 42%', zoom: 1.05 },
  ),
  photoDecor(
    15,
    ['portrait', 'outdoor', 'hero'],
    ['orange', 'blue', 'warm', 'light'],
    { position: '50% 47%', zoom: 1.04 },
  ),
  photoDecor(
    16,
    ['portrait', 'outdoor', 'hero'],
    ['blue', 'dark', 'cool'],
    { position: '50% 45%', zoom: 1.04 },
  ),
  photoDecor(
    17,
    ['portrait', 'outdoor', 'mobile', 'learning'],
    ['blue', 'green', 'cool', 'neutral'],
    { position: '50% 44%', zoom: 1.04 },
  ),
  photoDecor(
    18,
    ['portrait', 'outdoor', 'mobile', 'community'],
    ['blue', 'green', 'neutral', 'cool'],
    { position: '50% 45%', zoom: 1.04 },
  ),
  photoDecor(
    19,
    ['portrait', 'outdoor', 'learning'],
    ['blue', 'light', 'cool', 'neutral'],
    { position: '50% 45%', zoom: 1.06 },
  ),
  photoDecor(
    20,
    ['group', 'community', 'collaboration'],
    ['orange', 'warm', 'light', 'neutral'],
    { position: '50% 45%', zoom: 1.05 },
  ),
  photoDecor(
    21,
    ['group', 'workspace', 'collaboration', 'learning'],
    ['orange', 'warm', 'light', 'neutral'],
    { position: '50% 45%', zoom: 1.03 },
  ),
  photoDecor(
    22,
    ['group', 'community', 'outdoor'],
    ['blue', 'green', 'light', 'cool', 'neutral'],
    { position: '50% 43%', zoom: 1.04 },
  ),
  photoDecor(
    23,
    ['group', 'community', 'outdoor'],
    ['blue', 'light', 'cool', 'neutral'],
    { position: '50% 46%', zoom: 1.04 },
  ),
  photoDecor(
    24,
    ['group', 'community', 'collaboration'],
    ['green', 'orange', 'warm', 'light', 'neutral'],
    { position: '50% 45%', zoom: 1.04 },
  ),
  photoDecor(
    25,
    ['group', 'workshop', 'collaboration', 'learning'],
    ['green', 'orange', 'warm', 'light'],
    { position: '50% 44%', zoom: 1.03 },
  ),
  photoDecor(
    26,
    ['group', 'community', 'office', 'collaboration'],
    ['blue', 'green', 'light', 'neutral', 'cool'],
    { position: '50% 45%', zoom: 1.04 },
  ),
  photoDecor(
    27,
    ['group', 'community', 'mobile', 'outdoor'],
    ['blue', 'light', 'cool', 'neutral'],
    { position: '50% 46%', zoom: 1.04 },
  ),
  photoDecor(
    28,
    ['portrait', 'workspace', 'office', 'learning'],
    ['light', 'neutral', 'orange', 'warm'],
    { position: '50% 45%', zoom: 1.05 },
  ),
  photoDecor(
    29,
    ['portrait', 'outdoor', 'hero'],
    ['orange', 'blue', 'green', 'warm', 'light'],
    { position: '50% 45%', zoom: 1.06 },
  ),
  photoDecor(
    30,
    ['portrait', 'outdoor', 'hero'],
    ['blue', 'orange', 'cool', 'neutral'],
    { position: '62% 42%', zoom: 1.08 },
  ),
])

export const DEFAULT_DECORS = DEFAULT_DECOR_DATA
